---
title: 'How to Upload Controls'
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{How to Upload Controls}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

[Purpose:]{.underline} To upload batches of dry blood spots and whole
blood controls. Controls and samples have separate processes for uploads
and searches, and require different reference information. All control
uploads require metadata about the control being uploaded as well as
logistical information, such as what freezer the control is located in.

SampleDB supports two types of controls: Dry Blood Spots or Whole Blood. 
It is important to upload newly created controls immediately, because
recording extractions requires the control to exist in SampleDB.

These guidelines allow you to upload new controls, (including adding
references prior to the upload). Then, how to add these references in
the upload. Finally, how to document extractions linking to previous
controls in the database.

**Guidelines for Controls:** Open the "Controls" panel under
`References` > `Controls`.

**Create the references:** need `Batch`, `Strain` and `CompositionID`. Under
"Create new item":

a.  Select "Batch". Select the date the controls were created and click
    `Submit`.

b.  Select `Strain`. Can be uploaded manually or by a CSV with a single
    "Strains" column header. Strains should **always** be capitalized.

c.  Select "Composition". Compositions contain strain and proportion
    data. Composition IDs are generated automatically in the
    background, but may *optionally* be given a label during creation
    if that composition is already coded. Compositions should be
    uploaded via CSV. Use ";" to separate multi-strains, keep in the
    same order. Examples:

+---------------+-------------------+-------------------+
| > **Strains** | > **Percentages** | > **LegacyLabel** |
+===============+===================+===================+
| > 3D7;D6;HB3  | > 33;32;35        |                   |
+---------------+-------------------+-------------------+
| > W2;D6       | > 25;75           | > TS3-TC1         |
+---------------+-------------------+-------------------+
| > V1S         | > 100             |                   |
+---------------+-------------------+-------------------+

The first row has a 3-strain composition of 3D7, D6 and HB3 with
compositions of 33%, 32% and 35%. No label is provided so one will be
auto-generated (more information on this below).

The second row has a 2-strain composition; 25% W2, 75% D6. Its label
(TS3-TC1) will be used.

The third row has a monoclonal control (100% V1S) with no label. Since this
is a monoclonal, the label will just be the strain (in this case, 'V1S').

Labels are generated by combining the number of strains and an index
to make a unique identifier. **ONLY** provide a label if it is already
used. **New compositions** need auto generated labels.

- The auto-generated label produced is a function of the composition type (ie. 2-strain,
3 strain) and number of instances of the composition type in the database. For
example, if you have three 2-strain compositions in the database already and
add a new one, the resulting identifier would be `S3_4` where `S3` indicates
3-strain and `4` indicates this is the fourth instance.

### Steps to upload controls:

How to record Dry Blood Spot Controls (DBS) and Whole Blood (WB)
controls. In the bar, press "Upload Specimens". Where it says "Choose
Your Upload Type", select "Controls". Choose Storage Type ("DBS Sheet"
or "Whole Blood") and select "Create" under Action.

### Steps to Upload Dry Blood Spot Sheets (DBS Sheets):

In the top nav, hit "Upload Specimens". Where it says "Choose Your
Upload Type", select "Controls". Choose "DBS Sheet" under Storage Type
and select "Create" under Action.

#### Creating a DBS Sheet Upload:

1.  An example DBS Sheet Upload.

  CompositionID   Batch        SheetName   DBS\_FreezerName   DBS\_BasketName   DBS\_ShelfName   Density   Count   Comment
  --------------- ------------ ----------- ------------------ ----------------- ---------------- --------- ------- ---------
  DS3-DC1         2016-07-07   18          Hilda              Blue Box          Fourth Row       0.1       18      
  DS3-DC1         2016-07-07   18          Hilda              Blue Box          Fourth Row       1K        18      
  DS3-DC1         2016-07-07   18          Hilda              Blue Box          Fourth Row       10K       23      

a.  **CompositionID**: Refers to strain types and percentages involved
    (see "Guidelines for Controls" above). Find this information under
    `Update References` > `Controls`. Filter by strain and percentage.
    The specific identifier is under the "Label" column of the table.

b.  **Batch**: This is the control batch (see "Guidelines for Controls" above)

c.  **SheetName**: This is the sheet identifier. To identify the sheet
    the dry blood spots are on.

d.  **DBS_FreezerName, DBS_BasketName** **and DBS_ShelfName:**
    Location in the freezer

e.  **Density:** The parasitaemia level of the control.

f.  **Count:** The number of blood spots that were added to the sheet.

g.  **Comment:** An optional field to leave information about a DBS
    Sheet.

### Validation for Created DBS:

Uploads will be checked for completeness and validity.

1.  Composition IDs must exist to be used. Add under references (see
    **Guidelines for Controls**).

    a.  *Message: Composition IDs are not found in the database.*

2.  Batch must exist to be used. Add under references (see **Guidelines
    for Controls**).

    a.  *Message: Batch could not be found in the database*

3.  Location must exist to be used. Add under references

    a.  *Message: \"The following DBS\_FreezerName, DBS\_ShelfName,
        and/or DBS\_BasketName are not found in the database\"*

### Uploading Whole Blood (WB) Controls:

1.  Example of a Whole Blood Upload csv.

  Density   CompositionID   Batch        WB\_FreezerName   WB\_RackName   WB\_RackPosition   BoxRow   BoxColumn   BoxName               BoxBarcode   Comment
  --------- --------------- ------------ ----------------- -------------- ------------------ -------- ----------- --------------------- ------------ ---------
  1K        W2              2023-08-10   Graves            17             A1                 A        1           WB controls .5 pink                
  10K       DS1-DC4         2023-08-10   Graves            17             A1                 A        2           WB controls .5 pink                
  100       QS3-QC4         2023-08-10   Graves            17             A1                 A        3           WB controls .5 pink                

a.  **Density:** The parasitaemia level of the control. Use numerical
    > values or use a K (or k) to denote \"thousand\"

b.  **CompositionID**: In this column, record the composition **label**
    (see "Guidelines for Controls" above). Find this by going to `Update
    References` > `Controls`. Filter the compositions by strain and percentage.
    Use the ID in the "Label" column of the table.

c.  **Batch**: The control batch - it will look like a date, but must be
    already in sample DB (see "Guidelines for Controls" above)

d.  **WB\_FreezerName, WB\_BasketName and WB\_ShelfName:** Freezer
    location of DBS Bag

e.  **BoxRow and BoxColumn:** The row and column of tube within the box.

f.  **BoxName:** The ID for the box containing the tube.

g.  **BoxBarcode:** An optional field where a barcode can be added for
    the box, if one exists.

h.  **Comment:** An optional field where the user can leave info about a
    tube.

### Validation for Whole Blood (WB) Controls:

Uploads will be checked for completeness and validity.

-   CompositionID must exist in Sample DB to be used. Add under
    references (see Guidelines for Controls)

> *Message: Composition IDs are not found in the database.*

-   Batch must exist in Sample DB to be used. Add under references (see
    "Guidelines for Controls" above)

> *Message: Batch could not be found in the database*

-   Whole Blood Cryovial Box Location must exist to be used. Add under
    > references

> *\"The following WB\_FreezerName, WB\_RackName, and/or
> WB\_RackPosition are not found in the database\"*

-   Whole Blood Tubes must be uploaded to empty (existing!) locations

> *Message: "Uploading sample to Cryovial well location that already has
> an active sample"*

