---
title: 'How to Upload Extracted Controls'
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{How to Upload Extracted Controls}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

How to document control extractions in SampleDB for Dry Blood Spot
Controls and Whole Blood.

### Dry Blood Spot Control Extractions

#### Preparing your Dry Blood Spot Control-Extraction CSV:

SampleDB supports recording Dry Blood Spot extractions into micronix
plates.

  Batch        ControlUID    Barcode      Row   Column   PlateName                                ExtractedOn   SheetName   BagName   DBS\_FreezerName   DBS\_ShelfName   DBS\_BasketName   FreezerName   ShelfName   BasketName
  ------------ ------------- ------------ ----- -------- ---------------------------------------- ------------- ----------- --------- ------------------ ---------------- ----------------- ------------- ----------- ------------
  2016-07-07   1K\_DS6-DC2   4051125255   A     02       Plate\_1\_mixturecontrols\_ENV\_041922   2022-04-19    22          22        Hilda              Fourth Row       Blue Box          Ruth          Shelf 3     Controls
  2016-07-07   1K\_DS6-DC3   4051125528   A     03       Plate\_1\_mixturecontrols\_ENV\_041922   2022-04-19    22          22        Hilda              Fourth Row       Blue Box          Ruth          Shelf 3     Controls
  2016-07-07   1K\_DS6-DC4   4051125433   A     04       Plate\_1\_mixturecontrols\_ENV\_041922   2022-04-19    22          22        Hilda              Fourth Row       Blue Box          Ruth          Shelf 3     Controls

An example CSV with six (6) micronix tubes with DBS extractions. To
upload these extractions, the user should select "DBS" under "Control
Storage Type", and select "Extract" under "Action".

The columns are defined as follows: *NOTE: Column order does not
matter.*

a.  **Batch:** This is the control batch (see "Guidelines for Controls")

b.  **ControlUID:** This is the control that exists in the database that
    we want to link the extraction to.

    i.  This UID is created automatically by sampleDB and will need to
        be looked up. This can be done by searching for the controls
        in the "Search" panel using identifying information, e.g.
        location, composition (strain and/or percentages).

    ii. A strategy for preparing your extraction is to download the
        controls and adding the remaining columns to the sheet.

c.  **Barcode:** The barcode of the micronix tube.

d.  **Row, Column:** The position of the micronix tube with the
    extraction.

e.  **PlateName:** The name of the micronix plate.

f.  **PlateBarcode:** An optional field where a barcode can be added for
    the plate, if one exists.

g.  **ExtractedOn:** The date of the extraction.

h.  **SheetName:** This is the label of the sheet where the DBS Controls
    were sourced from.

i.  **BagLabel**: This is the label of the bag where the sheet came
    from.

j.  **DBS\_FreezerName, DBS\_BasketName and DBS\_ShelfName:** This is
    the location in the freezer where the DBS Control Sheet is
    located.

k.  **FreezerName, BasketName and ShelfName:** This is the location in
    the freezer where the micronix plate is located.

#### DBS Post-Extraction Effects:

After you record the extraction, the collection of blood spots that are
linked to the extraction will have its number of 'Exhausted' spots
updated.

If the number of exhausted spots equals the total after extraction, the
blood spot collection will be archived with an 'Exhausted' status.
Additionally, the text "Automatically archived as exhausted" will appear
in the reason field.

### Whole Blood Extractions

SampleDB supports recording whole blood extractions into micronix
plates.

#### Preparing your Whole Blood Extraction CSV:

  Batch        ControlUID   BoxRow   BoxColumn   BoxName               WB\_FreezerName   WB\_RackName   WB\_RackPosition   PlateName     FreezerName   ShelfName   BasketName   Row   Column   Barcode      ExtractedOn
  ------------ ------------ -------- ----------- --------------------- ----------------- -------------- ------------------ ------------- ------------- ----------- ------------ ----- -------- ------------ -------------
  2023-08-10   0.5\_W2      A        5           WB controls .5 pink   Graves            17             A1                 WB\_EXTRACT   TBD           TBD         unlocated    A     1        8888123451   2024-02-20
  2023-08-10   0.5\_W2      A        9           WB controls .5 pink   Graves            17             A1                 WB\_EXTRACT   TBD           TBD         unlocated    A     2        8888123452   2024-02-20
  2023-08-10   0.5\_W2      B        1           WB controls .5 pink   Graves            17             A1                 WB\_EXTRACT   TBD           TBD         unlocated    A     3        8888123453   2024-02-20
  2023-08-10   0.5\_W2      B        2           WB controls .5 pink   Graves            17             A1                 WB\_EXTRACT   TBD           TBD         unlocated    A     4        8888123454   2024-02-20

The above is an example CSV with four (4) whole blood extractions. To
upload these extractions, the user should select "Whole Blood" under
"Control Storage Type", and select "Extract" under "Action".

The columns are defined as followed:

l.  **Batch:** This is the control batch (see "Guidelines for Controls")

m.  **ControlUID:** This is the control that exists in the database that
    we want to link the extraction to.

    i.  This UID is created automatically by sampleDB and will need to
        be looked up. This can be done by searching for the controls
        in the "Search" panel using identifying information, e.g.
        location, composition (strain and/or percentages).

    ii. A strategy for preparing your extraction is to download the
        controls and adding the remaining columns to the sheet.

n.  **BoxRow, BoxColumn**: This is the location of the whole blood tube
    control in the cryovial box.

o.  **BoxName:** This is the id for the box that contains the whole
    blood tube.

p.  **BoxBarcode:** Optional field where a barcode can be added for the
    box, if one exists.

q.  **WB\_FreezerName, WB\_BasketName and WB\_ShelfName:** The plates
    location in the freezer

r.  **PlateName:** The name of the micronix plate.

s.  **Row, Column:** The position of the micronix tube with the
    extraction.

t.  **Barcode:** The barcode of the micronix tube.

u.  **ExtractedOn:** The date of the extraction.

*NOTE: Column order does not matter.*

#### Whole Blood Post-Extraction Effects:

After you record the extraction, the linked whole blood control will be
removed from the database.

