---
title: 'Searching SampleDB'
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Searching SampleDB}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

The section below will guide you on how to search for samples and
controls. It will detail the different searches available for different
sample types.

### Search Micronix Samples 

[Purpose:]{.underline}

To search for samples and find their location on a Micronix plate. You
can search by barcode OR by StudySubject OR by
StudySubject/CollectionDate/SpecimenType/Study. You can also search by
plate. If you would like to reset your search criteria, you may do
so by clicking "Reset Search Criteria". 

#### To Search by Single Barcode: 

1.  Click on "Search Samples"

2.  Type or copy/paste in barcode in the upper right hand 'Search...'
    field above the table.

3.  Search results will show in the window.

#### To search by multiple barcodes: 

1.  Create CSV with one column called "Barcodes" or "Barcode". Put all
    micronix barcodes you are searching for in this column.

2.  Click on "Multiple Barcodes" and click on "Browse" to upload the CSV
    you created.

3.  Search results will show in the window.

4.  Download the data if needed by clicking on the "Download" button.
    This will download a csv with all samples that were found in the
    search.

#### To Search by Plate: 

1.  Click on "Search, Delete & Archive Samples"

2.  Type the plate name into the "Container" field in the left hand bar.

3.  Search results will show in the window and can be downloaded.

#### To Search by Study Subject: 

1.  Click on "Search, Delete & Archive Samples"

2.  Click on Sample Type "Micronix" and click on "Single Study Subject"

3.  Type or copy/paste in Study Subject identifier

4.  Search results will show in the window.

#### To search for multiple study subject(s) (+/- date, study, specimen type): 

1.  Create CSV with one column called "StudySubject". Put all study
    subjects you are searching for in this column.

    a.  If you want to search by StudySubject AND CollectionDate, create
        one column with the StudySubject data and one column with the
        linked CollectionDate data. Save this CSV.

    b.  You may additionally include a SpecimenType and/or StudyCode
        column to refine the search further.

2.  Click on "Search Samples"

3.  Click on Sample Type "Micronix" and click on "Multiple Study
    Subjects"

4.  Click on "Browse" to upload the CSV you created.

5.  Search results will show in the window and can be downloaded using
    the "Download" button.

#### How to use the Advanced Micronix Barcode Search Utility:

At times, you may discover an irregularity on a plate, or want to know
if the samples on the plate match their position in the SampleDB
database. The Advanced Micronix Barcode search allows you to scan a
plate and will return the information detailed below.

1.  Scan a plate using a micronix plate scanner, and output the CSV

    a.  You may optionally create a CSV file with Barcode, Row, and
        Position columns.

2.  Ensure that the file is named after the plate name.

3.  Select the "Micronix" sample type in the "Search, Delete & Archive"
    tab, and then select the "Advanced..." hyperlink.

4.  Choose the appropriate micronix file type (NA, Traxcer or
    Visionmate).

5.  Hit Run Search.

    a.  If there are issues with your file upload, an error message will
        appear and tell you which columns were expected.

6.  Inspect the results that appear below run search. You can also
    download your file with these annotations which provides
    additional detail as noted in \#7 below.

    a.  Gray rows indicate a passing test.

    b.  Red rows indicated a failing test, with the number of instances
        that triggered this failure.

    c.  The following tests are performed, and will display these
        errors:

        i.  **NotFound** - A sample on the plate has a barcode that does
            not exist in SampleDB

            1.  This could occur if the sample was not uploaded.

            2.  Consider creating an upload file that contains the
                sample(s) with the correct position and plate
                information.

        ii. **IncorrectLocation** - A sample on the scanned plate is in
            a different position or plate (or both) than what is
            recorded in sampleDB.

            1.  This could occur if a sample was moved between plates or
                within a plate, and no move file was provided.

            2.  Consider uploading a new move file with this plate to
                fix this error.

        iii. **Archived** - The sample is in an "archived" status.

             1.  Use sample status and comment fields to guide you on
                 how to handle these.

7.  Optionally download your file with these annotations by clicking
    "Download Error Details".

    a.  Additional error statuses you may see are "Correct" or "Empty".
        These are to confirm that the sample barcode at a position
        matches what is in the database and the scanned file or that
        no sample exists at the position, respectively.

    b.  The columns in the downloaded file are as follows:

        i.  **CurrentWell** - This is the position that corresponds to
            the plate wells in the scanned file. There will always be
            96 wells \[A1 - H12\].

        ii. **Barcode** - This is the micronix barcode of the sample at
            the well in the scanned file. It can be NA if the well is
            empty.

        iii. **Status** - This can be any of the 5 statuses mentioned
             above (NotFound, IncorrectLocation, Archived, Correct, or
             Empty).

        iv. **DBWell** - This is the well that the sample was found in
            in the database.

        v.  **DBPlate** - This is the plate that the sample was found in
            in the database.

        vi. **DBBasket** - This is the basket the plate (DBPlate) was
            found in.

        vii. **DBFreezer** - This is the freezer the basket (DBBasket)
             is in.

        viii. **Study** - This is the study the sample (Barcode) is in.

        ix. **ID** - This is the study subject linked to the sample
            (Barcode).

        x.  **Date** - The collection date that is linked to the sample.
            This may be NA.

    c.  If a row has an 'Empty' status, all columns, excluding
        CurrentWell and Status, should have NA.

### Search for Cryovials

Cryovials can be searched for using the same filters as micronix
samples.

### Search Controls (DBS & WB)

Uploaded Dry Blood Spots and Whole Blood tubes can be viewed in the
"Search, Archive & Delete" Panel after selecting "Controls" under
"Search Type". You can then specify whether to search for "Dry Blood
Spots" and "Whole Blood".

In either case, you will be able to filter controls by "Batch", "Control
ID" (the generated identifier for the control), "Composition Type" (the
number of strains), "Strain" and "Percentage" (the composition). You may 
also search by location and by state and status as you can with Samples.

To search for extracted controls, you will need to select the "Samples"
search option under "Search Type", and select "Micronix" under "Sample
Type". Currently, uploaded extractions must be in micronix tubes. You
can search by the same filtering criteria that is available to micronix
samples.

Extracted controls are tied to controls in the database by the `Control UID`
and the `Batch`. With these two identifiers, you can find the exact control
that an extraction was derived from (and vice versa). The following will go
over how to do both workflows

##### Find the control used in an extraction

1. Set `Search Type` to `Samples` and `Sample Type` to `Micronix`.
2. Find the extraction (this will always have a study subject of `DNA (DBS)` or
`DNA (WB)`.
3. Save the `StudySubject`, `StudyCode` and `SpecimenType` information somewhere
as these will be used to search the controls. 
4. Now set `Search Type` to `Controls`.
5. Depending on the `SpecimenType`, choose `Whole Blood` (`DNA (WB)`) or
`DBS Sheet` (`DNA (DBS)`).
6. Find your control by filtering the `Batch` using your recorded `StudyCode`
and by filtering the `Control UID` using your recorded `StudySubject`. 

##### Find an extraction of the control

1. Set `Search Type` to `Controls` and `Sample Type` to `Micronix`.
2. Under `Control Type`, choose `Whole Blood` or `DBS Sheet`.
3. Find the control by using the available filters.
3. Save the `Control UID` and `Batch` information somewhere
as these will be used to search the extractions. 
4. Now set `Search Type` to `Samples` and `Sample Type` to `Micronix`.
5. Depending on the control type, filter the `Specimen Type` by `DNA (DBS)` or
`DNA (WB)` if the control was a dry blood spot or whole blood, respectively.
6. Find the extracts by filtering the `StudyCode` using your recorded `Batch`
and by filtering the `StudySubject` using your recorded `Control UID`. 


### Downloading your search results

You may download your search results by clicking the "Download" button
below the table. You may optionally choose to limit the samples included
in the download by selecting them in the table first.

*Important: The download works using the filters on the left hand side.
It does NOT work as you may expect if you use the top right filter. This
is because this top right filter is part of the table widget. The
recommendation is to use the filters on the left if you need to download
data. This may change in the future.*

