UIDelArchSamples <- function(){
  sidebarLayout(
    sidebarPanel(
      width = 2,
      # actionButton("verify_delarch", label = NULL),
      HTML("<h4>Delete and Archive Samples</h4>"),
      hr(),
      # fileInput("SearchByLabel", label = HTML("Barcode <h6>Single column named \"barcode\"</h6>")), actionButton("ClearSearchBarcodes", label = "Clear Barcodes"), textOutput("WarnSubjectBarcodeFileColnames"), textOutput("WarnSubjectBarcodeFileColnames2"),
      radioButtons("DelArchSearchBySampleType","Sample Type", c("All" = "all", "Micronix" = "micronix", "Cryovial" = "cryo", "RDT" = "rdt", "Paper" = "paper"), select = "micronix", inline = T),
      hr(),
      actionButton("DelArchSearchReset", width = '100%', label = "Reset Search Criteria", style="color: #fff; background-color: #337ab7; border-color: #2e6da4"),
      hr(),
      conditionalPanel(condition = "input.DelArchSearchBySampleType == \"micronix\"",
                       conditionalPanel(condition = "input.DelArchSearchByBarcodeType == \"multiple_barcodes\"",
                                        fileInput("DelArchSearchByBarcode", label = "Barcodes")),
                       conditionalPanel(condition = "input.DelArchSearchByBarcodeType == \"single_barcode\"",
                                        textInput("DelArchSearchBySingleBarcode", label = "Barcodes")),
                       radioButtons("DelArchSearchByBarcodeType", label = NULL, choices = list("Multiple Barcodes" = "multiple_barcodes", "Single Barcode" = "single_barcode"), selected = "multiple_barcodes"),
                       selectInput("DelArchSearchByPlate", label = "Plate Name", choices = c("", sampleDB::CheckTable(database = database, "micronix_plate")$name))),
      conditionalPanel(condition = "input.DelArchSearchBySampleType == \"cryo\"",
                       fileInput("DelArchSearchByCryovialLabels", label = "Sample Labels"),
                       selectInput("DelArchSearchByBox", label = "Box Name", choices = c("", sampleDB::CheckTable(database = database, "cryovial_box")$name))),
      hr(),
      selectizeInput("DelArchSearchByStudy", "Study", choices = c("", sampleDB::CheckTable(database = database, "study")$short_code)),
      conditionalPanel(condition = "input.DelArchSubjectUIDSearchType == \"individual\"",
                       selectizeInput("DelArchSearchBySubjectUID", label = "Study Subject", choices = c())),
      conditionalPanel(condition = "input.DelArchSubjectUIDSearchType == \"multiple\"",
                       fileInput("DelArchSearchBySubjectUIDFile", label = NULL)),
      radioButtons("DelArchSubjectUIDSearchType", label = NULL, choices = list("Single Study Subject" = "individual", "Multiple Study Subjects" = "multiple"), selected = "individual"),
      selectizeInput("DelArchSearchBySpecimenType", "Specimen Type", choices = c("", sampleDB::CheckTable(database = database, "specimen_type")$name)),
      dateRangeInput("DelArchdateRange", label = "Collection Dates", start = NA, end = NA) %>% suppressWarnings(),
      selectizeInput("DelArchSearchByLocation", "Storage Location", choices = c("", sampleDB::CheckTable("location")$location_name)),
      selectizeInput("DelArchSearchByLevelI", "Storage Location: Level I", choices = c("")),
      selectizeInput("DelArchSearchByLevelII", "Storage Location: Level II", choices = c("")),
      selectizeInput("DelArchSearchByState", "State", choices = c(Global$DefaultStateSearchTerm)),
      selectizeInput("DelArchSearchByStatus", "Status", choices = c(Global$DefaultStatusSearchTerm))
    ),
    mainPanel(
      width = 10,
      DT::dataTableOutput("DelArchSearchResultsTable"),
      hr(),
      selectizeInput("DelArchStatus", "Status", choices = c("", sampleDB:::.ViewArchiveStatuses(database = database)$name)),
      textInput(label = "Comment", inputId = "DelArchComment"),
      actionButton("ArchiveAction", width = '10.75%', label = "Archive Samples", style="color: #fff; background-color: #337ab7; border-color: #2e6da4"),
      hr(),
      actionButton("DeleteAction", width = '10.75%', label = "Delete Samples", style="color:#c4244c; background-color: #fff4f4; border-color: #c4244c"),
      verbatimTextOutput("DelArchMessage"),
      # conditionalPanel(condition = "input.RenameStudyDescription == \"xxx\"",
      #                  br(),
      #                  HTML("Type \"Yes\" if you would like to archive these samples."),
      #                  textInput("zzz", label = NULL),
      #                  actionButton("yes1", label = "Enter"),
      #                  verbatimTextOutput("yesout")),
    ))
}